ALTER TABLE users 
    ADD COLUMN IF NOT EXISTS username VARCHAR(100) UNIQUE,
    ADD COLUMN IF NOT EXISTS birthdate DATE NULL,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS location VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS organization VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS website TEXT NULL,
    ADD COLUMN IF NOT EXISTS phone VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS headline TEXT NULL,
    ADD COLUMN IF NOT EXISTS about TEXT NULL,
    ADD COLUMN IF NOT EXISTS skills JSONB NULL,
    ADD COLUMN IF NOT EXISTS socials JSONB NULL,
    ADD COLUMN IF NOT EXISTS photo TEXT NULL;